config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  resources :tasks
  root to: 'tasks#index'
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :task_to_labels, dependent: :destroy
  has_many :tasks, through: :task_to_labels
  validates :title, uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_to_labels, dependent: :destroy
  has_many :labels, through: :task_to_labels

  validates :task_name, presence: true
  validates :description, presence: true
  validates :deadline, presence: true

  enum rank:{ 低: 0, 中: 1, 高: 2 }

  paginates_per 10

  scope :search, -> (search_params) do
    return if search_params.blank?

    search_task_name(search_params[:task_name])
      .search_status(search_params[:status])
      .search_label(search_params[:label_id])
  end

  scope :search_task_name, ->(task_name) {where("task_name LIKE ?", "%#{task_name}%") if task_name.present? }
  scope :search_status, ->(status) {where(status: status) if status.present? }
  scope :search_label, ->(label_id) do
    if label_id.present?
      task_id = TaskToLabel.all.search_label_id(label_id).pluck(:task_id)
      where(id: task_id )
    end
  end
end

app/models/task_to_label.rb
class TaskToLabel < ApplicationRecord
  belongs_to :task
  belongs_to :label
  scope :search_label_id, ->(label_id) {where(label_id: label_id)}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy

  before_validation { email.downcase! }
  before_update :must_not_destroy_last_admin_user
  before_destroy :must_not_destroy_last_admin_user

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness:true,
            length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  private
  def must_not_destroy_last_admin_user
    user = User.find(id)
    if user.admin? && User.where(admin:true).count == 1
      errors.add(:base, '管理者権限は変更できません。少なくとも1人の管理者は必要です。')
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :login_check
  before_action :check_admin

  def index
    @users = User.includes(:tasks).order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    if @user.save
      redirect_to admin_users_path, info: "ユーザー登録しました"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @user_tasks = @user.tasks
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(params_user)
      redirect_to admin_users_path, info: "ユーザー情報を更新しました"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, info: "ユーザー情報を削除しました"
    else
      redirect_to admin_users_path, danger: '削除できません。少なくとも1人の管理者は必要です。'
    end
  end

  private
  def params_user
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin )
  end

  def set_user
    @user = User.find(params[:id])
  end

  def check_admin
    redirect_to tasks_path, danger: "あなたは管理者ではありません" unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to tasks_path, success: "ログインしました"
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:info] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show,:edit,:update,:destroy]
  before_action :login_check

  def index
    # 終了期限でソート
    if params[:sort_expired] == "true"
      @tasks = current_user.tasks.order(deadline: :asc).page(params[:page])
      # 優先順位でソート
    elsif params[:sort_rank] == "true"
      @tasks = current_user.tasks.order(rank: :desc).page(params[:page])
      # 検索機能
    elsif params[:search].present?
      @search_params = task_search_params
      @tasks = current_user.tasks.search(@search_params).includes(:labels).page(params[:page])
    else
      @tasks = current_user.tasks.order(created_at: :desc).page(params[:page]).per(10)
    end
  end

  def new
    @task = current_user.tasks.build
  end

  def create
    @task = @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to @task, success: "タスクが登録されました"
    else
      render "new"
    end
  end

  def show; end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to task_path, info: "タスクは更新されました"
    else
      render "edit"
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, info: "タスクは削除されました"
  end

  private

  def task_params
    params.require(:task).permit(:task_name, :description, :deadline, :status, :rank, { label_ids: [] })
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_search_params
    params.fetch(:search, {}).permit(:task_name, :status, :label_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_check_user, only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    if @user.save
      session[:user_id] = @user.id
      redirect_to tasks_path, info: "ユーザー登録しました"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    redirect_to tasks_path unless @user.id == current_user.id
  end

  private
  def params_user
    params.require(:user).permit(:name, :email, :password, :password_confirmation )
  end

  def login_check_user
    redirect_to tasks_path if logged_in?
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def login_check
    redirect_to new_session_path unless logged_in?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="task_header_nav">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to t("activerecord.view.user.list"), admin_users_path, class: "nav-link active btn btn-primary" %>
    </li>
  </ul>
</div>

<% if @user.errors.present? %>
  <% @user.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_with(model: [:admin, user],local: true) do |f| %>
  <div class="form-group">
    <%= f.label "name",id: 'user_name' %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "email",id: 'email' %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "admin",id: 'admin' %>
    <%= f.check_box :admin,{}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "password",id: 'password' %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "password_confirmation",id: 'password_confirmation' %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <%= f.submit t("helpers.submit.create"), class: "btn btn-primary" %>
<% end %>

app/views/admin/users/edit.html.erb
<h1><%= t("activerecord.view.user.edit") %></h1>
<%= render "form", user: @user %>

app/views/admin/users/index.html.erb
<h1><%= t("activerecord.view.user.list") %></h1>

<div class="task_header_nav">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to t("activerecord.view.user.new"), new_admin_user_path, class: "nav-link active btn btn-primary" %>
    </li>
    <li class="nav-item">
      <%= link_to t("activerecord.view.task.tasks_list"), tasks_path, class: "nav-link active btn btn-primary" %>
    </li>
  </ul>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= t('activerecord.attributes.user.name') %></th>
    <th><%= t('activerecord.attributes.user.email') %></th>
    <th><%= t('activerecord.attributes.user.admin') %></th>
    <th><%= t('activerecord.view.task.count') %></th>
    <th><%= t('activerecord.attributes.user.created_at') %></th>
    <th><%= t('activerecord.attributes.user.updated_at') %></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, admin_user_path(user) %></td>
      <td><%= user.email %></td>
      <td><%= user.admin %></td>
      <td><%= user.tasks.count %></td>
      <td><%= user.created_at %></td>
      <td><%= user.updated_at %></td>
      <td><%= link_to t("activerecord.view.user.edit"), edit_admin_user_path(user) %></td>
      <td><%= link_to t("activerecord.view.user.destroy"), admin_user_path(user), method: :delete,
                      data: { confirm: t( "activerecord.view.task.Are you sure you want to delete it?" )} %></td>
    </tr>
  <% end %>
  <%= paginate @users %>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>

  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1><%= t("activerecord.view.user.new") %></h1>
<%= render "form", user: @user %>

app/views/admin/users/show.html.erb
<h1><%= t("activerecord.view.user.admin_show") %></h1>

<div class="task_header_nav">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to t("activerecord.view.user.list"), admin_users_path, class: "nav-link active btn btn-primary" %>
    </li>
  </ul>
</div>

<h2><%= t("activerecord.view.user.info") %></h2>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= t('activerecord.attributes.user.name') %></th>
    <th><%= t('activerecord.attributes.user.email') %></th>
    <th><%= t('activerecord.attributes.user.admin') %></th>
    <th><%= t('activerecord.attributes.user.created_at') %></th>
    <th><%= t('activerecord.attributes.user.updated_at') %></th>
  </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @user.name %></td>
      <td><%= @user.email %></td>
      <td><%= @user.admin %></td>
      <td><%= @user.created_at %></td>
      <td><%= @user.updated_at %></td>
      <td><%= link_to t("activerecord.view.user.edit"), edit_admin_user_path(@user) %></td>
      <td><%= link_to t("activerecord.view.user.destroy"), admin_user_path(@user), method: :delete,
                      data: { confirm: t( "activerecord.view.task.Are you sure you want to delete it?" )} %></td>
    </tr>
  </tbody>
</table>

<h2><%= t("activerecord.view.task.tasks_list") %></h2>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= t('activerecord.attributes.task.task_name') %></th>
    <th><%= t('activerecord.attributes.task.description') %></th>
    <th><%= t('activerecord.attributes.task.deadline') %></th>
    <th><%= t('activerecord.attributes.task.status') %></th>
    <th><%= t('activerecord.attributes.task.rank') %></th>
    <th><%= t("activerecord.attributes.label.title") %></th>
  </tr>
  </thead>

  <tbody>
  <% @user_tasks.each do |task| %>
    <tr>
      <td><%= task.task_name %></td>
      <td><%= task.description %></td>
      <td><%= task.deadline %></td>
      <td><%= task.status %></td>
      <td><%= task.rank %></td>
      <td>
        <% task.labels.each do |label| %>
          <span class="label label-success"><%= label.title %></span>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <%= msg %>
      </div>
    <% end %>

      <div class="task_header_nav">
        <ul class="nav nav-pills">
        <li class="nav-item">
          <% if logged_in? %>
            <%= link_to t("activerecord.view.session.Log_out"), session_path(current_user.id), method: :delete, class: "nav-link active btn btn-primary" %>
            </li>
            <% if current_user.admin? %>
              <li class="nav-item">
                <%= link_to t("activerecord.view.user.admin_page"), admin_users_path, class: "nav-link active btn btn-primary" %>
              </li>
            <% end %>
          <% else %>
        <li class="nav-item">
          <%= link_to t("activerecord.view.session.Sign_up"), new_user_path, class: "nav-link active btn btn-primary" %>
        </li>
        <li class="nav-item">
          <%= link_to t("activerecord.view.session.Log_in"), new_session_path, class: "nav-link active btn btn-primary" %>
        </li>
          <% end %>
          </ul>
      </div>

    <%= yield %>

  </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="task_header_nav">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to t("activerecord.view.task.tasks_list"), tasks_path, class: "nav-link active btn btn-primary" %>
    </li>
  </ul>
</div>

<% if @task.errors.present? %>
  <% @task.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_with(model: task,local: true) do |f| %>
  <div class="form-group">
    <%= f.label "task_name",id: 'task_name' %>
    <%= f.text_field :task_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "description",id: 'task_description' %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "deadline",id: 'task_deadline' %>
    <%= f.date_field :deadline, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label "status",id: 'task_status' %>
    <%= f.select :status, [ t("activerecord.view.task.not_start"),t("activerecord.view.task.doing"),t("activerecord.view.task.done")], {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "rank",id: 'task_rank' %>
    <%= f.select :rank, Task.ranks.keys.to_a, {}, class: "form-control" %>
  </div>
  <div class="form-check">
    <%= f.collection_check_boxes(:label_ids, Label.all, :id, :title) %>
  </div>
  <%= f.submit t("helpers.submit.create"), class: "btn btn-primary" %>
<% end %>

app/views/tasks/edit.html.erb
<h1><%= t("activerecord.view.task.edit_task") %></h1>
<%= render "form" ,task: @task %>

app/views/tasks/index.html.erb
<h1><%= t("activerecord.view.task.tasks_list") %></h1>

<div class="task_header_nav">
<ul class="nav nav-pills">
  <li class="nav-item">
    <%= link_to t("activerecord.view.task.new_task"), new_task_path, class: "nav-link active btn btn-primary" %>
  </li>
  <li class="nav-item">
    <%= link_to t("activerecord.view.user.my_page"), user_path(current_user), class: "nav-link active btn btn-primary" %>
  </li>
  <li class="nav-item">
    <%= link_to t("activerecord.view.task.sort_deadline_desc"), tasks_path(sort_expired: "true" ),class: "nav-link active btn btn-primary" %>
  </li>
  <li class="nav-item">
    <%= link_to t("activerecord.view.task.sort_rank_desc"), tasks_path(sort_rank: "true" ),class: "nav-link active btn btn-primary" %>
  </li>
</ul>
</div>

<%= form_with(scope: :search, url: tasks_path, method: :get, local: true, class: "form-inline") do |s| %>
  <div class="form-group">
    <%= s.label(:task_name, t("activerecord.attributes.task.task_name")) %>
    <%= s.text_field :task_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= s.label(:status, t("activerecord.attributes.task.status")) %>
    <%= s.select :status, [ "",t("activerecord.view.task.not_start"),t("activerecord.view.task.doing"),t("activerecord.view.task.done")], {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= s.label(:label, t("activerecord.attributes.label.title")) %>
    <%= s.select :label_id, Label.pluck(:title, :id), { include_blank: true} %>
  </div>
    <%= s.submit t("activerecord.view.task.search"),class:"btn btn-primary" %>
  <% end %>

  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= t('activerecord.attributes.task.task_name') %></th>
      <th><%= t('activerecord.attributes.task.description') %></th>
      <th><%= t('activerecord.attributes.task.deadline') %></th>
      <th><%= t('activerecord.attributes.task.status') %></th>
      <th><%= t('activerecord.attributes.task.rank') %></th>
      <th><%= t("activerecord.attributes.label.title") %></th>
    </tr>
    </thead>
  
    <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= link_to task.task_name, task_path(task) %></td>
      <td><%= task.description %></td>
      <td><%= task.deadline %></td>
      <td><%= task.status %></td>
      <td><%= task.rank %></td>
      <td>
        <% task.labels.each do |label| %>
          <span class="label label-success"><%= label.title %></span>
        <% end %>
      </td>
      <td><%= link_to t("activerecord.view.task.edit_task"), edit_task_path(task) %></td>
      <td><%= link_to t("activerecord.view.task.destroy_task"), task, method: :delete,
                      data: { confirm: t( "activerecord.view.task.Are you sure you want to delete it?" )} %></td>
    </tr>
    <% end %>
    <%= paginate @tasks %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>

    </tbody>
  </table>

app/views/tasks/new.html.erb
<h1><%= t("activerecord.view.task.new_task") %></h1>
<%= render "form" ,task: @task %>

app/views/tasks/show.html.erb
<h1><%= t("activerecord.view.task.task_show") %></h1>

<div class="task_header_nav">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to t("activerecord.view.task.tasks_list"), tasks_path, class: "nav-link active btn btn-primary" %>
    </li>
  </ul>
</div>

<table class="table table-striped">
  <tbody>
  <tr>
    <th><%= t('activerecord.attributes.task.task_name') %></th>
    <td><%= @task.task_name %></td>
  </tr>
  <tr>
    <th><%= t('activerecord.attributes.task.description') %></th>
    <td><%= @task.description %></td>
  </tr>
  <tr>
    <th><%= t('activerecord.attributes.task.deadline') %></th>
    <td><%= @task.deadline %></td>
  </tr>
  <tr>
    <th><%= t('activerecord.attributes.task.status') %></th>
    <td><%= @task.status %></td>
  </tr>
  <tr>
    <th><%= t('activerecord.attributes.task.rank') %></th>
    <td><%= @task.rank %></td>
  </tr>
  <tr>
    <th><%= t("activerecord.attributes.label.title") %></th>
    <td>
      <% @task.labels.each do |label| %>
        <span class="label label-success"><%= label.title %></span>
      <% end %>
    </td>
  </tr>
  </tbody>
</table>

<%= link_to t("activerecord.view.task.edit_task"), edit_task_path(@task), class: "btn btn-primary", role: "button" %>
<%= link_to t("activerecord.view.task.destroy_task"), @task, method: :delete, data: { confirm: t( "activerecord.view.task.Are you sure you want to delete it?" )}, class: "btn btn-primary", role: "button" %>

app/views/users/new.html.erb
<h1><%= t("activerecord.view.session.Sign_up") %></h1>

<% if @user.errors.present? %>
  <% @user.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_with(model: @user,local: true) do |f| %>
  <div class="form-group">
    <%= f.label "name",id: 'user_name' %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "email",id: 'email' %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "password",id: 'password' %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "password_confirmation",id: 'password_confirmation' %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <%= f.submit t("helpers.submit.create"), class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<h1><%= t("activerecord.view.user.my_page") %></h1>

<div class="task_header_nav">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to t("activerecord.view.task.tasks_list"), tasks_path, class: "nav-link active btn btn-primary" %>
    </li>
  </ul>
</div>

<table class="table table-striped">
  <tbody>
  <tr>
    <th><%= t('activerecord.attributes.user.name') %></th>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <th><%= t('activerecord.attributes.user.email') %></th>
    <td><%= @user.email %></td>
  </tr>
  </tbody>
</table>